name: pick

task_name: pick

image_shape: &image_shape [3, 84, 84]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    # image:
    #     shape: *image_shape
    #     type: rgb
    point_cloud:
      shape: [512, 3]
      type: point_cloud
    agent_pos:
      shape: [8]
      type: low_dim
  action:
    shape: [8]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.adroit_dataset.AdroitDataset
  zarr_path: data/final_pick_sim.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
