camera:
  width: 1280
  height: 720
  max_depth: 2.0
  scale: 1000.0
  intrinsics:
    - [623.53829072, 0.0, 640.0]
    - [0.0, 623.53829072, 360.0]
    - [0.0, 0.0, 1.0]
  extrinsics:
    - [0.0, 1.0, 0.0, 0.0]
    - [0.4940094, -0.0, -0.8694565, -0.30628583]
    - [-0.8694565, -0.0, -0.4940094, 1.5511894]
    - [0.0, 0.0, 0.0, 1.0]

processing:
  crop_bounds: [0.3, 1.3, -0.8, 0.8, 0.001, 1.0] # x_min, x_max, y_min, y_max, z_min, z_max

workspace:
  x_range: [0.65, 1.1]
  y_range: [0.45, 0.66]
  z_range: [-0.7, 0.0]
